server:
  port: 0

spring:
  application:
    name: collector

  kafka:
    bootstrap-servers: localhost:29092

collector:
  topic:
    user-actions: stats.user-actions.v1

grpc:
  server:
    port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
