server:
  port: 0

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        max-attempts: 10
        max-interval: 10000
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    ru.practicum.stats.collector: DEBUG
    org.apache.kafka: INFO
    org.springframework: ERROR

collector:
  topic:
    user-actions: stats.user-actions.v1